# examples/run_figures.py

import time
from pathlib import Path

import matplotlib.pyplot as plt

from ics_thermal.config import run_test_case
from plot_results import (
    plot_temperatures,
    plot_heatflows,
    plot_modes,
    plot_newton_iterations,
    plot_compare_ics_pcs,
    plot_phase_planes_ics_pcs,
)

# Figures are written to the repository root with names that match the
# figure numbers in the manuscript.
REPO_ROOT = Path(__file__).resolve().parent.parent
OUTDIR = REPO_ROOT


def _save_all(names):
    """
    Save and close every open figure, in creation order.

    plot_compare_ics_pcs and plot_phase_planes_ics_pcs each leave several
    figures open at once, so plt.savefig() alone would capture whichever
    was created last rather than the one intended.  The figure numbers
    returned by plt.get_fignums() are in creation order, so zipping them
    with the caller's name list gives a stable, position-independent
    mapping.

    Raises if the number of names does not match the number of open
    figures, which catches a change in panel order immediately.
    """
    fignums = plt.get_fignums()
    if len(fignums) != len(names):
        raise RuntimeError(
            f"_save_all expected {len(names)} open figures, "
            f"found {len(fignums)}: {fignums}"
        )
    for num, name in zip(fignums, names):
        fig = plt.figure(num)
        out = OUTDIR / name
        fig.savefig(out, dpi=300, bbox_inches="tight")
        plt.close(fig)
        print(f"[+] {out}")


# ----------------------------------------------------------------------
# Figure numbering used throughout
# ----------------------------------------------------------------------
#  Figure 1   system schematic (not generated by this script)
#  Figure 2   Test A  temperature trajectories
#  Figure 3   Test A  internode heat flow
#  Figure 4   Test A  constraint heat flows
#  Figure 5   Test A  phase planes
#  Figure 6   Test A  constraint-activation timeline
#  Figure 7   Test A  Newton iterations per macrostep
#  Figure 8   Test B  temperature trajectories
#  Figure 9   Test B  constraint-activation raster
#  Figure 10  Test B  Newton iterations per macrostep
#  Figure 11  Test C  temperature trajectories
#  Figure 12  Test C  constraint flow trajectories
#  Figure 13  Test C  constraint-activation raster
#  Figure 14  Test C  Newton iterations per macrostep
#  Figure 15  energy residual vs time        (run_projection_study.py)
#  Figure 16  residual vs step size          (run_projection_study.py)
#
# Panel order within the plotting helpers, which determines the mapping:
#   plot_compare_ics_pcs       -> 1 temperatures, 2 internode flows,
#                                 3 constraint flows, 4 activation timeline
#   plot_phase_planes_ics_pcs  -> 1 phase-plane scatter,
#                                 2 activation heatmaps (ICS and PCS)
# ----------------------------------------------------------------------


def run_test_A():
    print("\n=== Running Test A (N=2) ===")
    t0 = time.perf_counter()
    ics, pcs = run_test_case("A", N=2, solver="both",
                             t_final=13.0, dt_ics=0.05, h_pcs=0.0002)
    t1 = time.perf_counter()
    print(f"ICS CPU = {t1 - t0:.3f}s, Newton iters = {sum(ics['n_iter'])}")
    print(f"PCS steps = {pcs['icount']}")

    # ---- Figures 2, 3, 4, 6 : comparison panels ----------------------
    plot_compare_ics_pcs(ics, pcs, nodes=[0, 1])
    _save_all([
        "fig02_testA_temperatures.png",          # Figure 2
        "fig03_testA_internode_heatflows.png",   # Figure 3
        "fig04_testA_constraint_heatflows.png",  # Figure 4
        "fig06_testA_activation_timeline.png",   # Figure 6
    ])

    # ---- Figures 5 : phase planes ------------------------------------
    plot_phase_planes_ics_pcs(ics, pcs)
    _save_all([
        "fig05_testA_phase_planes.png",          # Figure 5
        "figA_extra_activation_raster.png",      # not in the paper
    ])

    # ---- Figure 7 : Newton iterations --------------------------------
    plot_newton_iterations(ics)
    _save_all([
        "fig07_testA_newton_iterations.png",     # Figure 7
    ])

    return ics, pcs


def run_test_B():
    print("\n=== Running Test B (N=10) ===")
    t0 = time.perf_counter()
    ics = run_test_case("B", N=10, solver="ICS",
                        t_final=13.0, dt_ics=0.05)
    t1 = time.perf_counter()
    print(f"ICS CPU = {t1 - t0:.3f}s, Newton iters = {sum(ics['n_iter'])}")

    t0 = time.perf_counter()
    pcs = run_test_case("B", N=10, solver="PCS",
                        t_final=13.0, h_pcs=0.0002)
    t1 = time.perf_counter()
    print(f"PCS CPU = {t1 - t0:.3f}s, steps = {pcs['icount']}")

    # ---- Figure 8 : temperatures -------------------------------------
    plot_compare_ics_pcs(ics, pcs, nodes=[0, 3, 6, 9])
    _save_all([
        "fig08_testB_temperatures.png",              # Figure 8
        "figB_extra_internode_heatflows.png",        # not in the paper
        "figB_extra_constraint_heatflows.png",       # not in the paper
        "figB_extra_activation_timeline.png",        # not in the paper
    ])

    # ---- Figure 9 : constraint-activation raster ---------------------
    plot_phase_planes_ics_pcs(ics, pcs)
    _save_all([
        "figB_extra_phase_planes.png",               # not in the paper
        "fig09_testB_activation_raster.png",         # Figure 9
    ])

    # ---- Figure 10 : Newton iterations -------------------------------
    plot_newton_iterations(ics)
    _save_all([
        "fig10_testB_newton_iterations.png",         # Figure 10
    ])

    return ics, pcs


def run_test_C():
    print("\n=== Running Test C (N=10) ===")
    t0 = time.perf_counter()
    ics = run_test_case("C", N=10, solver="ICS",
                        t_final=13.0, dt_ics=0.05)
    t1 = time.perf_counter()
    print(f"ICS CPU = {t1 - t0:.3f}s, Newton iters = {sum(ics['n_iter'])}")

    t0 = time.perf_counter()
    pcs = run_test_case("C", N=10, solver="PCS",
                        t_final=13.0, h_pcs=2.5e-6)
    t1 = time.perf_counter()
    print(f"PCS CPU = {t1 - t0:.3f}s, steps = {pcs['icount']}")

    # ---- Figures 11 and 12 -------------------------------------------
    plot_compare_ics_pcs(ics, pcs, nodes=[0, 3, 6, 9])
    _save_all([
        "fig11_testC_temperatures.png",              # Figure 11
        "figC_extra_internode_heatflows.png",        # not in the paper
        "fig12_testC_constraint_flows.png",          # Figure 12
        "figC_extra_activation_timeline.png",        # not in the paper
    ])

    # ---- Figure 13 : constraint-activation raster --------------------
    plot_phase_planes_ics_pcs(ics, pcs)
    _save_all([
        "figC_extra_phase_planes.png",               # not in the paper
        "fig13_testC_activation_raster.png",         # Figure 13
    ])

    # ---- Figure 14 : Newton iterations -------------------------------
    plot_newton_iterations(ics)
    _save_all([
        "fig14_testC_newton_iterations.png",         # Figure 14
    ])

    return ics, pcs


if __name__ == "__main__":
    run_test_A()
    run_test_B()
    run_test_C()
